const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,x-team-password','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(status,body)=>({statusCode:status,headers:{...CORS,'Content-Type':'application/json'},body:JSON.stringify(body)});
const pass=e=>(e.headers['x-team-password']||e.headers['X-Team-Password'])===(process.env.PRESS_TEAM_PASSWORD||process.env.PRESS_PASSWORD);
const prompts={
 noticia:['Analizar mi noticia','Revisa el texto como tutor de periodismo escolar. No reescribas la noticia completa. Identifica si responde qué, quién, cuándo, dónde, cómo y por qué; señala fortalezas y máximo 5 aspectos por mejorar. Da sugerencias concretas y pedagógicas.'],
 investigar:['Ayúdame a investigar','Actúa como tutor de investigación periodística escolar. Ayúdame a convertir la idea en una pregunta investigable, proponer fuentes y entrevistas, y señalar qué información falta. No inventes datos ni fuentes.'],
 entrevista:['Preparar entrevista','Ayuda a preparar una entrevista periodística escolar. Propón preguntas abiertas, de profundización, de contraste y una pregunta de cierre. No respondas las preguntas por el estudiante.'],
 revisar:['Revisar mi texto','Revisa claridad, coherencia, cohesión, ortografía y estructura. Señala problemas y explica cómo mejorarlos, pero no sustituyas todo el texto por una versión escrita por ti.'],
 preguntas:['Hazme preguntas','Formula preguntas que ayuden al estudiante a profundizar su investigación, argumento o relato. No escribas el contenido por él.']
};
exports.handler=async e=>{if(e.httpMethod==='OPTIONS')return{statusCode:200,headers:CORS,body:''};if(e.httpMethod!=='POST'||!pass(e))return json(401,{error:'No autorizado.'});if(!process.env.GEMINI_API_KEY)return json(503,{error:'La IA aún no está configurada. Agrega GEMINI_API_KEY en las variables de Netlify.'});let d;try{d=JSON.parse(e.body||'{}')}catch{return json(400,{error:'Datos inválidos.'})};const key=d.tool;if(!prompts[key])return json(400,{error:'Herramienta no válida.'});const text=String(d.text||'').trim();if(text.length<20)return json(400,{error:'Escribe primero una idea o texto más completo.'});const [title,instruction]=prompts[key];const system=`Eres NORA, asistente editorial pedagógico de Prensa Normalista, un periódico escolar de una Escuela Normal en Colombia. Tu función es acompañar a estudiantes del equipo de prensa. ${instruction} Responde en español claro, respetuoso y breve. No inventes hechos, cifras, fuentes, citas ni nombres. Si el estudiante presenta afirmaciones que requieren verificación, indícalo. La autoría final debe permanecer en el estudiante.`;
 const body={contents:[{role:'user',parts:[{text:`${system}\n\nHerramienta: ${title}\n\nMaterial del estudiante:\n${text}`}]}]};try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key='+encodeURIComponent(process.env.GEMINI_API_KEY),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const out=await r.json();if(!r.ok)return json(502,{error:out.error?.message||'La IA no pudo responder.'});const answer=out.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('\n')||'No se recibió respuesta.';return json(200,{tool:key,answer});}catch(err){return json(500,{error:'No fue posible conectar con la IA.'});}};
