const { getStore } = require('@netlify/blobs');
function escapeHtml(str){return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function escAttr(s){return escapeHtml(s).replace(/\n/g,' ')}
exports.handler=async event=>{
  let slug=(event.queryStringParameters&&event.queryStringParameters.slug)||'';
  if(!slug && event.path){const m=event.path.match(/\/noticia\/([^/?#]+)/);if(m)slug=decodeURIComponent(m[1]);}
  const siteUrl=process.env.URL||`https://${event.headers.host}`;
  const store=getStore({name:'articles',siteID:process.env.SITE_ID,token:process.env.BLOBS_TOKEN,consistency:'strong'});
  const notFound=()=>({statusCode:404,headers:{'Content-Type':'text/html; charset=utf-8'},body:`<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Noticia no encontrada — Prensa Escuela</title><link rel="stylesheet" href="/styles.css"></head><body><main class="article-page"><h1 class="article-title">Esta noticia no existe o fue retirada</h1><a class="back-link" href="/">← Volver a portada</a></main></body></html>`});
  if(!slug)return notFound();
  const article=await store.get(`article:${slug}`,{type:'json'});if(!article)return notFound();
  try{const views=(await store.get(`views:${slug}`,{type:'json'}))||0;await store.setJSON(`views:${slug}`,views+1)}catch(e){}
  const imageUrl=article.hasImage?`${siteUrl}/api/image?slug=${encodeURIComponent(slug)}`:null;
  const paragraphs=article.content.split(/\n{2,}/).map(p=>`<p>${escapeHtml(p).replace(/\n/g,'<br>')}</p>`).join('\n');
  const date=new Date(article.publishedAt).toLocaleDateString('es-CO',{day:'numeric',month:'long',year:'numeric'});
  const tagClass=article.category.includes('Opinión')?'tag--opinion':article.category.includes('Voz')?'tag--voice':'tag--noticia';
  const video = article.videoUrl && /^https?:\/\/(www\.)?(youtube\.com\/watch\?v=|youtu\.be\/)/i.test(article.videoUrl) ? (()=>{const m=article.videoUrl.match(/(?:v=|youtu\.be\/)([A-Za-z0-9_-]{6,})/);return m?`<div class="media-box"><h3>🎥 Video</h3><div class="video-wrap"><iframe src="https://www.youtube.com/embed/${m[1]}" title="Video relacionado" loading="lazy" allowfullscreen></iframe></div></div>`:''})() : '';
  const audio = article.audioUrl && /^https?:\/\//i.test(article.audioUrl) ? `<div class="media-box"><h3>🎙️ Audio / podcast</h3><audio controls preload="none" src="${escAttr(article.audioUrl)}"></audio></div>` : '';
  const share=`<div class="share-box"><strong>Comparte esta publicación</strong><div class="share-actions"><a class="share-btn share-whatsapp" target="_blank" rel="noopener" href="https://wa.me/?text=${encodeURIComponent(article.title+' — '+siteUrl+'/noticia/'+slug)}">WhatsApp</a><button class="share-btn" onclick="navigator.clipboard.writeText(location.href).then(()=>this.textContent='¡Enlace copiado!')">Copiar enlace</button></div></div>`;
  const html=`<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escAttr(article.title)} — Prensa Escuela</title><meta name="description" content="${escAttr(article.excerpt)}"><meta property="og:type" content="article"><meta property="og:title" content="${escAttr(article.title)}"><meta property="og:description" content="${escAttr(article.excerpt)}"><meta property="og:url" content="${siteUrl}/noticia/${slug}">${imageUrl?`<meta property="og:image" content="${imageUrl}">`:`<meta property="og:image" content="${siteUrl}/escudo.png">`}<meta name="twitter:card" content="${imageUrl?'summary_large_image':'summary'}"><link rel="icon" type="image/png" href="/escudo.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"></head><body><header class="masthead"><a href="/" class="masthead-link"><img class="masthead-crest" src="/escudo.png" alt="Escudo de la Escuela Normal Superior de Manatí"><div class="masthead-edition">EDICIÓN DIGITAL · ${date}</div><h1 class="masthead-title">Prensa Escuela</h1><div class="masthead-rule"></div></a></header><main class="article-page"><span class="tag ${tagClass}">${escapeHtml(article.category)}</span><h1 class="article-title">${escapeHtml(article.title)}</h1><p class="article-byline">Por ${escapeHtml(article.author)}${article.studentGrade?` · ${escapeHtml(article.studentGrade)}`:''} · ${date}</p>${imageUrl?`<img class="article-image" src="${imageUrl}" alt="${escAttr(article.title)}">`:''}<div class="article-body">${paragraphs}</div>${video}${audio}${share}<a class="back-link" href="/">← Volver a portada</a></main></body></html>`;
  return{statusCode:200,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'},body:html};
};
