const {getStore}=require('@netlify/blobs');
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,x-press-password,x-team-password','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'};
const store=()=>getStore({name:'articles',siteID:process.env.SITE_ID,token:process.env.BLOBS_TOKEN,consistency:'strong'});
const pass=e=>{const supplied=e.headers['x-team-password']||e.headers['X-Team-Password']||e.headers['x-press-password']||e.headers['X-Press-Password'];return !!supplied&&(supplied===process.env.PRESS_PASSWORD||supplied===process.env.PRESS_TEAM_PASSWORD)};
const json=(status,body)=>({statusCode:status,headers:{...CORS,'Content-Type':'application/json'},body:JSON.stringify(body)});
const slugify=t=>String(t||'proyecto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,70)||'proyecto';
exports.handler=async e=>{const s=store();if(e.httpMethod==='OPTIONS')return{statusCode:200,headers:CORS,body:''};if(!pass(e))return json(401,{error:'Clave del equipo incorrecta.'});
if(e.httpMethod==='GET'){const idx=(await s.get('lab-index',{type:'json'}))||[];const full=await Promise.all(idx.map(x=>s.get(`lab:${x.id}`,{type:'json'})));return json(200,full.filter(Boolean));}
let d={};try{d=JSON.parse(e.body||'{}')}catch{return json(400,{error:'Datos inválidos.'})};
if(e.httpMethod==='POST'){if(!d.title||!d.author||!d.type)return json(400,{error:'Completa título, autor y tipo de proyecto.'});const id=`lab-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const item={id,title:String(d.title).trim(),author:String(d.author).trim(),grade:String(d.grade||'').trim(),type:String(d.type).trim(),stage:String(d.stage||'idea'),researchQuestion:String(d.researchQuestion||'').trim(),sources:String(d.sources||'').trim(),interviews:String(d.interviews||'').trim(),draft:String(d.draft||'').trim(),notes:String(d.notes||'').trim(),aiUses:Array.isArray(d.aiUses)?d.aiUses:[],hasPhoto:false,photoType:'',videoUrl:String(d.videoUrl||'').trim(),audioUrl:String(d.audioUrl||'').trim(),hasVideoFile:false,hasAudioFile:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(d.photoBase64&&d.photoType){await s.set(`lab-media:image:${id}`,Buffer.from(d.photoBase64,'base64'),{metadata:{contentType:d.photoType}});item.hasPhoto=true;item.photoType=d.photoType}if(d.videoBase64&&d.videoType){await s.set(`lab-media:video:${id}`,Buffer.from(d.videoBase64,'base64'),{metadata:{contentType:d.videoType}});item.hasVideoFile=true}if(d.audioBase64&&d.audioType){await s.set(`lab-media:audio:${id}`,Buffer.from(d.audioBase64,'base64'),{metadata:{contentType:d.audioType}});item.hasAudioFile=true}await s.setJSON(`lab:${id}`,item);const idx=(await s.get('lab-index',{type:'json'}))||[];idx.unshift({id,title:item.title,author:item.author,grade:item.grade,type:item.type,stage:item.stage,updatedAt:item.updatedAt});await s.setJSON('lab-index',idx);return json(200,item)}
const id=e.queryStringParameters?.id||d.id;if(!id)return json(400,{error:'Falta el proyecto.'});const item=await s.get(`lab:${id}`,{type:'json'});if(!item)return json(404,{error:'Proyecto no encontrado.'});
if(e.httpMethod==='PUT'){
if(d.action==='reject'){item.stage='rechazada';item.notes=String(d.notes||item.notes||'').trim();item.updatedAt=new Date().toISOString();await s.setJSON(`lab:${id}`,item);return await syncIndex(s,item)}
if(d.action==='review'){item.stage='revision';item.notes=String(d.notes||item.notes||'').trim();item.updatedAt=new Date().toISOString();await s.setJSON(`lab:${id}`,item);return await syncIndex(s,item)}
if(d.action==='approve'){if(!item.draft)return json(400,{error:'El proyecto no tiene un borrador para publicar.'});const articles=(await s.get('index',{type:'json'}))||[];const base=slugify(item.title),used=new Set(articles.map(x=>x.slug));let slug=base,n=2;while(used.has(slug))slug=`${base}-${n++}`;const publishedAt=new Date().toISOString();const article={slug,title:item.title,author:item.author,category:`${item.type} · Laboratorio`,content:item.draft,hasImage:item.hasPhoto||false,publishedAt,excerpt:item.draft.replace(/\s+/g,' ').trim().slice(0,180),featured:false,studentGrade:item.grade,videoUrl:item.videoUrl||'',audioUrl:item.audioUrl||''};if(item.hasPhoto){const r=await s.getWithMetadata(`lab-media:image:${id}`,{type:'arrayBuffer'});if(r)await s.set(`image:${slug}`,Buffer.from(r.data),{metadata:{contentType:r.metadata?.contentType||item.photoType||'image/jpeg'}})}if(item.hasVideoFile){article.videoUrl=`/api/lab-media?id=${encodeURIComponent(id)}&kind=video`}if(item.hasAudioFile){article.audioUrl=`/api/lab-media?id=${encodeURIComponent(id)}&kind=audio`}await s.setJSON(`article:${slug}`,article);articles.push({slug,title:article.title,author:article.author,category:article.category,publishedAt,excerpt:article.excerpt,hasImage:article.hasImage,featured:false,studentGrade:item.grade,videoUrl:article.videoUrl,audioUrl:article.audioUrl});await s.setJSON('index',articles);item.stage='publicada';item.publishedSlug=slug;item.updatedAt=publishedAt;await s.setJSON(`lab:${id}`,item);return await syncIndex(s,item,{slug})}
Object.assign(item,{title:d.title!==undefined?String(d.title).trim():item.title,author:d.author!==undefined?String(d.author).trim():item.author,grade:d.grade!==undefined?String(d.grade).trim():item.grade,type:d.type!==undefined?String(d.type).trim():item.type,stage:d.stage!==undefined?String(d.stage):item.stage,researchQuestion:d.researchQuestion!==undefined?String(d.researchQuestion).trim():item.researchQuestion,sources:d.sources!==undefined?String(d.sources).trim():item.sources,interviews:d.interviews!==undefined?String(d.interviews).trim():item.interviews,draft:d.draft!==undefined?String(d.draft).trim():item.draft,notes:d.notes!==undefined?String(d.notes).trim():item.notes,aiUses:Array.isArray(d.aiUses)?d.aiUses:item.aiUses,videoUrl:d.videoUrl!==undefined?String(d.videoUrl||'').trim():item.videoUrl||'',audioUrl:d.audioUrl!==undefined?String(d.audioUrl||'').trim():item.audioUrl||'',updatedAt:new Date().toISOString()});if(d.removePhoto){await s.delete(`lab-media:image:${id}`);item.hasPhoto=false}if(d.photoBase64&&d.photoType){await s.set(`lab-media:image:${id}`,Buffer.from(d.photoBase64,'base64'),{metadata:{contentType:d.photoType}});item.hasPhoto=true;item.photoType=d.photoType}if(d.videoBase64&&d.videoType){await s.set(`lab-media:video:${id}`,Buffer.from(d.videoBase64,'base64'),{metadata:{contentType:d.videoType}});item.hasVideoFile=true}if(d.audioBase64&&d.audioType){await s.set(`lab-media:audio:${id}`,Buffer.from(d.audioBase64,'base64'),{metadata:{contentType:d.audioType}});item.hasAudioFile=true}await s.setJSON(`lab:${id}`,item);if(item.publishedSlug){const article=await s.get(`article:${item.publishedSlug}`,{type:'json'});if(article){article.title=item.title;article.author=item.author;article.category=`${item.type} · Laboratorio`;article.content=item.draft;article.studentGrade=item.grade;article.videoUrl=item.hasVideoFile?`/api/lab-media?id=${encodeURIComponent(id)}&kind=video`:(item.videoUrl||'');article.audioUrl=item.hasAudioFile?`/api/lab-media?id=${encodeURIComponent(id)}&kind=audio`:(item.audioUrl||'');article.hasImage=!!item.hasPhoto;if(item.hasPhoto){const rr=await s.getWithMetadata(`lab-media:image:${id}`,{type:'arrayBuffer'});if(rr)await s.set(`image:${item.publishedSlug}`,Buffer.from(rr.data),{metadata:{contentType:rr.metadata?.contentType||item.photoType||'image/jpeg'}})}else if(d.removePhoto)await s.delete(`image:${item.publishedSlug}`);article.excerpt=item.draft.replace(/\s+/g,' ').trim().slice(0,180);await s.setJSON(`article:${item.publishedSlug}`,article);const articles=(await s.get('index',{type:'json'}))||[];const ai=articles.findIndex(x=>x.slug===item.publishedSlug);if(ai>=0)articles[ai]={...articles[ai],title:article.title,author:article.author,category:article.category,excerpt:article.excerpt,hasImage:article.hasImage,videoUrl:article.videoUrl,audioUrl:article.audioUrl,studentGrade:article.studentGrade};await s.setJSON('index',articles)}}return await syncIndex(s,item)}
if(e.httpMethod==='DELETE'){await s.delete(`lab:${id}`);for(const k of ['image','video','audio'])await s.delete(`lab-media:${k}:${id}`);const idx=(await s.get('lab-index',{type:'json'}))||[];await s.setJSON('lab-index',idx.filter(x=>x.id!==id));return json(200,{ok:true})}return json(405,{error:'Método no permitido.'})};
async function syncIndex(s,item,extra={}){const idx=(await s.get('lab-index',{type:'json'}))||[];const i=idx.findIndex(x=>x.id===item.id);if(i>=0)idx[i]={...idx[i],title:item.title,author:item.author,grade:item.grade,type:item.type,stage:item.stage,updatedAt:item.updatedAt};await s.setJSON('lab-index',idx);return json(200,{...item,...extra})}