const { getStore } = require('@netlify/blobs');
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,x-press-password,x-team-password','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'};
const store=()=>getStore({name:'articles',siteID:process.env.SITE_ID,token:process.env.BLOBS_TOKEN,consistency:'strong'});
const pass=e=>(e.headers['x-team-password']||e.headers['X-Team-Password']||e.headers['x-press-password']||e.headers['X-Press-Password'])===(process.env.PRESS_TEAM_PASSWORD||process.env.PRESS_PASSWORD);
const json=(status,body)=>({statusCode:status,headers:{...CORS,'Content-Type':'application/json'},body:JSON.stringify(body)});
exports.handler=async e=>{const s=store();if(e.httpMethod==='OPTIONS')return{statusCode:200,headers:CORS,body:''};if(!pass(e))return json(401,{error:'Clave del equipo incorrecta.'});
 if(e.httpMethod==='GET'){const idx=(await s.get('lab-index',{type:'json'}))||[];const full=await Promise.all(idx.map(x=>s.get(`lab:${x.id}`,{type:'json'})));return json(200,full.filter(Boolean));}
 let d={};try{d=JSON.parse(e.body||'{}')}catch{return json(400,{error:'Datos inválidos.'})};
 if(e.httpMethod==='POST'){if(!d.title||!d.author||!d.type)return json(400,{error:'Completa título, autor y tipo de proyecto.'});const id=`lab-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const item={id,title:String(d.title).trim(),author:String(d.author).trim(),grade:String(d.grade||'').trim(),type:String(d.type).trim(),stage:String(d.stage||'idea'),researchQuestion:String(d.researchQuestion||'').trim(),sources:String(d.sources||'').trim(),interviews:String(d.interviews||'').trim(),draft:String(d.draft||'').trim(),notes:String(d.notes||'').trim(),aiUses:Array.isArray(d.aiUses)?d.aiUses:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await s.setJSON(`lab:${id}`,item);const idx=(await s.get('lab-index',{type:'json'}))||[];idx.unshift({id,title:item.title,author:item.author,grade:item.grade,type:item.type,stage:item.stage,updatedAt:item.updatedAt});await s.setJSON('lab-index',idx);return json(200,item);}
 const id=e.queryStringParameters?.id||d.id;if(!id)return json(400,{error:'Falta el proyecto.'});const item=await s.get(`lab:${id}`,{type:'json'});if(!item)return json(404,{error:'Proyecto no encontrado.'});
 if(e.httpMethod==='PUT'){Object.assign(item,{title:d.title!==undefined?String(d.title).trim():item.title,author:d.author!==undefined?String(d.author).trim():item.author,grade:d.grade!==undefined?String(d.grade).trim():item.grade,type:d.type!==undefined?String(d.type).trim():item.type,stage:d.stage!==undefined?String(d.stage):item.stage,researchQuestion:d.researchQuestion!==undefined?String(d.researchQuestion).trim():item.researchQuestion,sources:d.sources!==undefined?String(d.sources).trim():item.sources,interviews:d.interviews!==undefined?String(d.interviews).trim():item.interviews,draft:d.draft!==undefined?String(d.draft).trim():item.draft,notes:d.notes!==undefined?String(d.notes).trim():item.notes,aiUses:Array.isArray(d.aiUses)?d.aiUses:item.aiUses,updatedAt:new Date().toISOString()});await s.setJSON(`lab:${id}`,item);const idx=(await s.get('lab-index',{type:'json'}))||[];const i=idx.findIndex(x=>x.id===id);if(i>=0)idx[i]={...idx[i],title:item.title,author:item.author,grade:item.grade,type:item.type,stage:item.stage,updatedAt:item.updatedAt};await s.setJSON('lab-index',idx);return json(200,item);}
 if(e.httpMethod==='DELETE'){await s.delete(`lab:${id}`);const idx=(await s.get('lab-index',{type:'json'}))||[];await s.setJSON('lab-index',idx.filter(x=>x.id!==id));return json(200,{ok:true});}return json(405,{error:'Método no permitido.'});};
