const { getStore } = require('@netlify/blobs');
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,x-press-password','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'};
const store=()=>getStore(process.env.SITE_ID&&process.env.BLOBS_TOKEN?{name:'articles',siteID:process.env.SITE_ID,token:process.env.BLOBS_TOKEN,consistency:'strong'}:{name:'articles',consistency:'strong'});
const auth=e=>(e.headers['x-press-password']||e.headers['X-Press-Password'])===process.env.PRESS_PASSWORD&&!!process.env.PRESS_PASSWORD;
const json=(n,b)=>({statusCode:n,headers:{...CORS,'Content-Type':'application/json'},body:JSON.stringify(b)});
const code=()=>`VE-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
exports.handler=async e=>{const s=store();if(e.httpMethod==='OPTIONS')return{statusCode:200,headers:CORS,body:''};
 if(e.httpMethod==='POST'){let d;try{d=JSON.parse(e.body||'{}')}catch{return json(400,{error:'Datos inválidos.'})};if(!d.title||!d.author||!d.grade||!d.type||!d.content||!d.email)return json(400,{error:'Completa todos los campos obligatorios, incluido tu correo electrónico.'});const email=String(d.email).trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return json(400,{error:'Escribe un correo electrónico válido.'});if(String(d.content).trim().length<80)return json(400,{error:'El texto debe tener al menos 80 caracteres.'});const id=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const item={id,code:code(),version:1,title:String(d.title).trim(),author:String(d.author).trim(),email,grade:String(d.grade).trim(),type:String(d.type).trim(),content:String(d.content).trim(),videoUrl:String(d.videoUrl||'').trim(),hasImage:false,submittedAt:new Date().toISOString(),status:'pending',feedback:'',feedbackAt:null,feedbackSentAt:null,versions:[]};if(d.imageBase64&&d.imageType){await s.set(`voice-image:${id}`,Buffer.from(d.imageBase64,'base64'),{metadata:{contentType:d.imageType}});item.hasImage=true}await s.setJSON(`voice:${id}`,item);const list=(await s.get('voices-index',{type:'json'}))||[];list.unshift({id,code:item.code,title:item.title,author:item.author,email:item.email,grade:item.grade,type:item.type,submittedAt:item.submittedAt,status:item.status});await s.setJSON('voices-index',list);return json(200,{ok:true,code:item.code,id:item.id});}
 const qp=e.queryStringParameters||{}; if(e.httpMethod==='GET' && qp.email && qp.code){const list=(await s.get('voices-index',{type:'json'}))||[];const hit=list.find(x=>String(x.email).toLowerCase()===String(qp.email).toLowerCase()&&x.code===qp.code);if(!hit)return json(404,{error:'No encontramos un envío con ese correo y código.'});const item=await s.get(`voice:${hit.id}`,{type:'json'});if(!item)return json(404,{error:'Envío no encontrado.'});return json(200,{id:item.id,code:item.code,version:item.version,title:item.title,author:item.author,grade:item.grade,type:item.type,content:item.content,status:item.status,feedback:item.feedback||'',submittedAt:item.submittedAt,videoUrl:item.videoUrl||'',hasImage:!!item.hasImage,publishedSlug:item.publishedSlug||null});}
 if(!auth(e))return json(401,{error:'No autorizado.'});
 if(e.httpMethod==='GET'){const list=(await s.get('voices-index',{type:'json'}))||[];const full=await Promise.all(list.map(async x=>{const i=await s.get(`voice:${x.id}`,{type:'json'});return i||x}));return json(200,full);}
 let d={};try{d=JSON.parse(e.body||'{}')}catch{return json(400,{error:'Datos inválidos.'})};
 if(e.httpMethod==='PUT'){if(!d.id)return json(400,{error:'Falta el identificador.'});const item=await s.get(`voice:${d.id}`,{type:'json'});if(!item)return json(404,{error:'Texto no encontrado.'});if(d.action==='revision'){item.status='revision';item.feedback=String(d.feedback||'').trim();item.feedbackAt=item.feedback?new Date().toISOString():null;}else if(d.action==='reject'){item.status='rejected';item.feedback=String(d.feedback||'').trim();item.feedbackAt=item.feedback?new Date().toISOString():null;}else if(typeof d.feedback==='string'){item.feedback=d.feedback.trim();item.feedbackAt=item.feedback?new Date().toISOString():null;item.status=item.feedback?'reviewed':'pending';}if(d.markFeedbackSent)item.feedbackSentAt=new Date().toISOString();await s.setJSON(`voice:${d.id}`,item);const list=(await s.get('voices-index',{type:'json'}))||[];const i=list.findIndex(x=>x.id===d.id);if(i>=0)list[i]={...list[i],status:item.status,feedback:item.feedback,feedbackAt:item.feedbackAt,feedbackSentAt:item.feedbackSentAt};await s.setJSON('voices-index',list);return json(200,{ok:true,item});}
 if(e.httpMethod==='DELETE'){const id=e.queryStringParameters?.id;if(!id)return json(400,{error:'Falta el identificador.'});const item=await s.get(`voice:${id}`,{type:'json'});if(item?.hasImage)await s.delete(`voice-image:${id}`);await s.delete(`voice:${id}`);const list=(await s.get('voices-index',{type:'json'}))||[];await s.setJSON('voices-index',list.filter(x=>x.id!==id));return json(200,{ok:true});}return json(405,{error:'Método no permitido.'});};