[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/noticia/*"
  to = "/.netlify/functions/article?slug=:splat"
  status = 200

[[redirects]]
  from = "/api/articles"
  to = "/.netlify/functions/articles"
  status = 200

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200

[[redirects]]
  from = "/api/voices"
  to = "/.netlify/functions/voices"
  status = 200

[[redirects]]
  from = "/api/voice-approve"
  to = "/.netlify/functions/voice-approve"
  status = 200

[[redirects]]
  from = "/api/team"
  to = "/.netlify/functions/team"
  status = 200

[[redirects]]
  from = "/api/team-image"
  to = "/.netlify/functions/team-image"
  status = 200

[[redirects]]
  from = "/api/voice-feedback"
  to = "/.netlify/functions/voice-feedback"
  status = 200
