[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/noticia/*"
  to = "/.netlify/functions/article?slug=:splat"
  status = 200

[[redirects]]
  from = "/api/articles"
  to = "/.netlify/functions/articles"
  status = 200

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200
